# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'BeatBeat' do

  pod 'googleapis', :path => '.'
#  pod 'Soundcloud', :git => 'https://github.com/delannoyk/SoundcloudSDK', :branch => 'develop'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '3.0.0'
  pod 'NVActivityIndicatorView'
  pod "BusyNavigationBar"	
end


